### ISSUE TITLE
bug in train.py

### ISSUE THREAD

**Issue by wsgdrfz** [hardmaru/estool#8] opened 2018-04-16 07:36 UTC
1. Run `python train.py robo_ant -n 8 -t 4`

```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 9 slots
that were requested by the application:
  /Users/wsgdrfz/anaconda2/bin/python

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 440, in <module>
    if "parent" == mpi_fork(args.num_worker+1): os.exit()
  File "train.py", line 414, in mpi_fork
    subprocess.check_call(["mpirun", "-np", str(n), sys.executable] +['-u']+ sys.argv, env=env)
  File "/Users/wsgdrfz/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '9', '/Users/wsgdrfz/anaconda2/bin/python', '-u', 'train.py', 'bullet_racecar', '-n', '8', '-t', '4']' returned non-zero exit status 1

wsgdrfz@wsgdrfz-MBP /Users/wsgdrfz/Downloads/estool-master                                                                                           
⚡ python train.py robo_ant -n 8 -t 4
pybullet build time: Feb  9 2018 16:40:49
current_dir=/Users/wsgdrfz/anaconda2/lib/python2.7/site-packages/pybullet_envs/bullet
current_dir=/Users/wsgdrfz/anaconda2/lib/python2.7/site-packages/pybullet_envs/bullet
['mpirun', '-np', '9', '/Users/wsgdrfz/anaconda2/bin/python', 'train.py', 'robo_ant', '-n', '8', '-t', '4']
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 9 slots
that were requested by the application:
  /Users/wsgdrfz/anaconda2/bin/python

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 440, in <module>
    if "parent" == mpi_fork(args.num_worker+1): os.exit()
  File "train.py", line 414, in mpi_fork
    subprocess.check_call(["mpirun", "-np", str(n), sys.executable] +['-u']+ sys.argv, env=env)
  File "/Users/wsgdrfz/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '9', '/Users/wsgdrfz/anaconda2/bin/python', '-u', 'train.py', 'robo_ant', '-n', '8', '-t', '4']' returned non-zero exit status 1

```

2. If I ignore `if "parent" == mpi_fork(args.num_worker+1): os.exit()`

```

pybullet build time: Apr 16 2018 07:12:17
current_dir=/usr/local/lib/python3.6/site-packages/pybullet_envs/bullet
current_dir=/usr/local/lib/python3.6/site-packages/pybullet_envs/bullet
size of model 10176
(16_w,32)-aCMA-ES (mu_w=9.2,w_1=19%) in dimension 10176 (seed=911961, Mon Apr 16 08:34:09 2018)
('process', 0, 'out of total ', 1, 'started')
('training', 'robo_ant')
('population', 32)
('num_worker', 8)
('num_worker_trial', 4)
Traceback (most recent call last):
  File "train.py", line 441, in <module>
    main(args)
  File "train.py", line 395, in main
    master()
  File "train.py", line 315, in master
    reward_list_total = receive_packets_from_slaves()
  File "train.py", line 243, in receive_packets_from_slaves
    comm.Recv(result_packet, source=i)
  File "mpi4py/MPI/Comm.pyx", line 285, in mpi4py.MPI.Comm.Recv
mpi4py.MPI.Exception: MPI_ERR_RANK: invalid rank

```

My env:
python3: 3.6.5
mpi4py: 3.0.0

**Comment by hardmaru** [comment] 2018-04-16 07:40
Thanks for reporting, especially with the detailed information about your
setup.

Can you also let me know which OS and how many CPU cores you are using?

**Comment by wsgdrfz** [comment] 2018-04-16 07:46
OS: macOS High Sierra 10.13.3
cpu.core_count: 2
cpu.brand_string:                                                                                                              machdep.cpu.brand_string: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz

**Comment by hardmaru** [comment] 2018-04-16 09:07
2 cores might be too few for MPI to run 9 (8+1) processes. My 2014 macbook
pro has 8 cores.

I think this might run on 2 cores:

python train.py bullet_racecar -n 2 -t 16

**Comment by wsgdrfz** [comment] 2018-04-16 11:16
Same error...

**Comment by wsgdrfz** [comment] 2018-04-16 11:29
Maybe I can try to just use the model.py and try to train on my own.

**Comment by ruiwang2uber** [comment] 2018-04-16 18:41
@wsgdrfz  Could it be related to the mpi setup with your machine? Do you use openmpi? I googled and found a seemingly similar error FYI: https://github.com/open-mpi/ompi/issues/3133

I am able to run the code for training on my Mac and Desktop without any problem.  I found that my issues at the beginning of using the code were all with either my MPI setup or openAI gym/simulation engine. 

@hardmaru  Did you notice memory leak when you were using the code for training? 

For example, I experienced memory leak that prevented me from going more than 300 iterations on my computer when training agents in BipedWalkerHardCore-v2 from openAI gym?

Later I figured out that for BipedWalkerHardCore-v2, it is due to the Box2D related code in openAI gym. I've submitted a issue to them and later a pull request that include my proposed fix.

https://github.com/openai/gym/issues/980
https://github.com/openai/gym/pull/997

**Comment by wsgdrfz** [comment] 2018-04-16 19:05
Thanks for referring this. I do little things about mpi and that's why I found one similar problem in other proj but I don't know how to fix it.

Now I just use the es algorithms and write my own code. Thansk!

**Comment by hardmaru** [comment] 2018-04-16 19:42
Hi @ruiwang2uber

I think I did notice that BipedWalkerHardCore-v2 leaks some memory, but was lucky/spoiled enough to be using machines with [416GB](https://techcrunch.com/2017/03/09/googles-compute-engine-now-offers-machines-with-up-to-64-cpu-cores-416gb-of-ram/) RAM :)

Thanks for letting them know about the issue I hope it will be resolved soon.

**Comment by ruiwang2uber** [comment] 2018-04-17 03:06
@hardmaru @wsgdrfz Thanks!

**Comment by olegklimov** [comment] 2018-04-18 20:26
Hi there. Nice fix from you @ruiwang2uber  :+1:

**Comment by hardmaru** [comment] 2018-04-18 20:34
@olegklimov since this is a small fix on the memory leak, and most likely won't affect the environment and reproducibility, would you be keeping the carracing-v0 task can remain as it is and no need to bump up to v1?

**Comment by olegklimov** [comment] 2018-04-18 21:11
For now it's a fix for BipedalWalker. Version yes, I believe there's no reason for a version bump.

**Comment by trougnouf** [comment] 2018-05-21 16:25
The initial problem disappears with ```export OMPI_MCA_rmaps_base_oversubscribe=1```

**Comment by hardmaru** [comment] 2018-05-25 21:45
Hi, thanks for pitching in. I'm going to close this issue.

**Closed by hardmaru** 2018-05-25 21:45 UTC

**Comment by AliBaheri** [comment] 2018-10-23 15:53
@ruiwang2uber Would you please provide more information how did you solve the issue. I face with similar issue here:

`  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '2', '/home/baheri/.virtualenvs/worldmodels/bin/python', '-u', '05_train_controller.py', 'car_racing', '--num_worker', '1', '--num_worker_trial', '2', '--num_episode', '4', '--max_length', '1000', '--eval_steps', '25']' returned non-zero exit status 1.`
